name: weather
description: Weather service project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/auth/svg/
    - assets/weather/svg/
    - assets/weather/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
    
    - family: Roboto Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    
    - family: Roboto Medium
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
